const app=document.getElementById("app");
const hud=document.getElementById("hud");
let state=null,snap=null,session=localStorage.getItem("rd.session")||"";
function H(){return session?{Authorization:"Bearer "+session,"Content-Type":"application/json"}:{"Content-Type":"application/json"};}
async function api(p,o={}){const r=await fetch(p,{...o,headers:{...H(),...(o.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||r.statusText);return d;}
const route=()=>location.hash.replace(/^#/,"")||"/";
const money=c=>{const n=(c||0)/100;return Number.isInteger(n)?"$"+n:"$"+n.toFixed(2);};
function clock(sec){sec=Math.max(0,sec|0);const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return String(h).padStart(2,"0")+"h "+String(m).padStart(2,"0")+"m "+String(s).padStart(2,"0")+"s";}
function toast(t){const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2800);}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">",'"':""","'":"&#39;"}[c]));}
function auth(){if(state&&state.me)return "<p class='sub'>Signed in as <b>"+esc(state.me.handle)+"</b> · "+state.me.money+"</p>";return "<form id='reg'><label>Handle</label><input name='handle' required minlength='3'><button class='btn' style='margin-top:8px'>Enter</button></form>";}
function board(){const t=snap.trackers,h=t.throne.holder,gap=snap.gapCents||0;
const king=snap.houseEmpty?"<div class='throne'><div class='kicker'>EMPTY DAIS</div><h1>THE HOUSE</h1><p class='sub'>$1 takes the chair.</p></div>":"<div class='throne border-throne'><div class='kicker'>LIVING KING</div><h1>"+esc(h&&h.handle||"—")+"</h1><div class='meta'><span>Held <b id='reign'>"+clock(t.throne.reignSeconds)+"</b></span><span>Gap <b>"+money(gap)+"</b></span><span>Armor <b id='armor'>"+(t.throne.armorSeconds?clock(t.throne.armorSeconds):"off")+"</b></span></div><div class='gap'><i style='width:"+Math.max(6,Math.min(100,100-gap/100))+"%'></i></div></div>";
const rows=(snap.board||[]).map(u=>"<a class='row "+((u.loadout&&u.loadout.border)||"")+"' href='#/u/"+encodeURIComponent(u.handle)+"'><div class='rank'>#"+u.rank+"</div><div><div class='handle'>"+esc(u.handle)+"</div><div class='sub'>"+esc(u.title)+"</div></div><div class='money'>"+u.money+"</div></a>").join("");
const feed=(snap.events||[]).map(e=>"<div><b>"+esc(e.handle)+"</b> "+esc(e.type)+(e.cents?" · "+money(e.cents):"")+"</div>").join("")||"<div>Board is cold.</div>";
return king+"<div class='grid'><div>"+(rows||"<p class='sub'>No kings yet.</p>")+"</div><div><div class='kicker'>KILL FEED</div><div class='feed'>"+feed+"</div></div></div>";}
function shove(){return "<div class='kicker'>PAY DESK</div><h2>Shove</h2><p class='sub'>"+(state&&state.demo?"DEMO MODE — instant score.":"Stripe checkout.")+"</p><form id='shoveForm'><label>Dollars</label><input name='dollars' type='number' min='1' value='5'><div class='chips'><button type='button' data-c='1'>$1</button><button type='button' data-c='5'>$5</button><button type='button' data-c='20'>$20</button></div><button class='btn block'>SHOVE</button></form><div class='chips'><button data-sku='FLEX'>Flex $3</button><button data-sku='BANNER_NIGHT'>Banner $8</button><button data-sku='LOCK_DRIP'>Drip $12</button><button data-sku='THRONE_ARMOR_15'>Armor $5</button></div>"+auth();}
function locker(){const me=state&&state.me;const items=((state&&state.cosmetics)||[]).map(c=>{const have=me&&me.unlocks&&me.unlocks.includes(c.id);return "<div class='card "+(have?"":"locked")+"'><div>"+esc(c.name)+"</div><div class='sub'>"+(have?"owned":c.tier||"locked")+"</div>"+(have?"<button class='btn ghost' data-equip='"+c.slot+":"+c.id+"'>Equip</button>":"")+"</div>";}).join("");return "<div class='kicker'>LOCKER</div><div class='locker'>"+items+"</div>";}
function page(){const r=route();if(r.startsWith("/shove"))return shove();if(r.startsWith("/locker"))return locker();if(r.startsWith("/throne")){const h=snap.trackers.throne.holder;return h?"<div class='throne border-throne'><div class='kicker'>THE THRONE</div><h1>"+esc(h.handle)+"</h1><p>"+h.money+"</p><p class='sub'>Held "+clock(snap.trackers.throne.reignSeconds)+"</p></div>":"<div class='throne'><h1>Cold chair</h1></div>";}if(r.startsWith("/daily"))return "<div class='kicker'>DAILY</div>"+(snap.trackers.daily||[]).map((d,i)=>"<div class='row'><div class='rank'>#"+(i+1)+"</div><div>"+esc(d.handle)+"</div><div class='money'>"+d.money+"</div></div>").join("")||"<p class='sub'>No spend today.</p>";if(r.startsWith("/hall"))return "<div class='kicker'>HALL</div><p class='sub'>Open after a few dethrones.</p>";return board();}
function hudBar(){const me=state&&state.me;if(!me){hud.classList.add("hidden");return;}hud.classList.remove("hidden");const t=snap.trackers.me;hud.innerHTML="<div class='sub'>You #"+((t&&t.rank)||"—")+" · "+money((t&&t.cents)||me.lifetimeCents)+"</div><a class='btn' href='#/shove'>SHOVE</a>";}
async function draw(){if(!snap){app.innerHTML="<p>Connecting…</p>";return;}app.innerHTML=page();hudBar();bind();
document.getElementById("watchers").textContent=(snap.trackers.watchers||0)+" watching";
const h=snap.trackers.throne.holder;document.title=h?"THRONE · "+h.handle:"RICH DETECTOR";}
function bind(){const reg=document.getElementById("reg");if(reg)reg.onsubmit=async e=>{e.preventDefault();const handle=new FormData(e.target).get("handle");try{let out;try{out=await api("/api/login",{method:"POST",body:JSON.stringify({handle})});}catch(err){out=await api("/api/register",{method:"POST",body:JSON.stringify({handle})});}session=out.session;localStorage.setItem("rd.session",session);state.me=out.user;toast("You are in.");draw();}catch(err){toast(err.message);}};
const sf=document.getElementById("shoveForm");if(sf)sf.onsubmit=e=>{e.preventDefault();play("SHOVE",Number(e.target.dollars.value)*100);};
document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{const i=document.querySelector("[name=dollars]");if(i)i.value=b.dataset.c;});
document.querySelectorAll("[data-sku]").forEach(b=>b.onclick=()=>play(b.dataset.sku));
document.querySelectorAll("[data-equip]").forEach(b=>b.onclick=async()=>{const p=b.dataset.equip.split(":");try{const out=await api("/api/me/equip",{method:"POST",body:JSON.stringify({slot:p[0],id:p[1]})});state.me=Object.assign({},state.me,out.user);toast("Equipped");}catch(err){toast(err.message);}});}
async function play(sku,cents){try{const out=await api("/api/checkout",{method:"POST",body:JSON.stringify({sku,cents})});if(out.url){location.href=out.url;return;}snap=out.snapshot;state.me=out.result.user;toast(out.result.dethroned?"Ended "+out.result.dethroned.handle:"Play landed");location.hash="#/";draw();}catch(err){toast(err.message);}}
function connect(){const ws=new WebSocket((location.protocol==="https:"?"wss":"ws")+"://"+location.host+"/ws");
ws.onmessage=ev=>{const msg=JSON.parse(ev.data);if(msg.type==="board.snapshot"){snap=msg.data;if(state)state.snapshot=msg.data;draw();}if(msg.type==="trackers.tick"&&snap){snap.trackers=msg.data;const r=document.getElementById("reign"),a=document.getElementById("armor");if(r)r.textContent=clock(msg.data.throne.reignSeconds);if(a)a.textContent=msg.data.throne.armorSeconds?clock(msg.data.throne.armorSeconds):"off";}};
ws.onclose=()=>setTimeout(connect,1500);}
async function boot(){try{state=await api("/api/state");snap=state.snapshot;}catch(e){snap={board:[],events:[],trackers:{throne:{},heat:{m5:{},m10:{},m60:{}},daily:[]},houseEmpty:true};}await draw();connect();}
window.addEventListener("hashchange",draw);boot();
